version: '3'
services:
  mysql:
    build:
        context: .
        dockerfile: Dockerfile.release.mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 35792030
        MYSQL_DATABASE: ChannelX
    ports:
     - "3306:3306"
    volumes:
     - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
     - alpine_mysql:/var/lib/mysql
     - gmail_api:/root/.credentials
  backend:
    build: 
        context: .
        dockerfile: Dockerfile.release
    depends_on: 
     - "mysql"
    links:
     - "mysql:my.sql"
    ports:
     - "6969:6969"
     - "4200:4200"
    stdin_open: true
    tty: true
    environment:
        PKG_NAME: github.com/ChannelX-ITU/ChannelX-Project/backend
volumes:
  alpine_node_modules:
  alpine_mysql:
  gmail_api:
