root_path = "."

watch_target_dirs = [".", "server/", "channel/"]
watch_file_ext = [".go", ".toml"]

build_target_dir = "/app"
build_target_name = "server"
build_command = "go"
build_options = ["build", "-v"]

# start command will be `build_target_dir/build_target_name start_options`
# in this case $GOPATH/bin/myserver -v
start_options = []

# default true, but it's possible to make this fale, when
# running a program that doesn't persist as a process
restart_process = true
